name: Development - Deploy Terraform
run-name: Build number ${{ github.run_id }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        options:
        - dev
        default: dev
      infrapath:
        description: 'Path to the infrastructure code'
        type: string
        default: 'none'

env:
  RUN_ID: ${{ github.run_id }}
  RG_BACKEND: 'rg-rbcz-tfstateaicoe-dev-weu-001'
  ST_BACKEND: 'statninfradev001'
  CONTAINER_BACKEND: 'infradev001'

jobs:
  workflow-info:
    name: 'Workflow Information and Check'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Environment Selection
      run: echo "User @${{ github.actor }} deploying to ${{ github.event.inputs.environment }}"
    
    - name: Run ID
      run: echo "Run ID ${{ env.RUN_ID }}"

    - name: Check Path
      run: |
        if [ -d "./infrastructure/dev/${{ github.event.inputs.infrapath }}" ]; then
          echo "Path /infrastructure/dev/${{ github.event.inputs.infrapath }} exist"
        else
          echo "!!! Path /infrastructure/dev/${{ github.event.inputs.infrapath }} does not exist !!!"
          echo "Please use one of the following subfolders as path:"
          ls -l infrastructure/dev
          exit 1
        fi
    
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: [workflow-info]
    if: github.event.inputs.infrapath != 'none'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Terraform Version
      run: terraform version

    - name: Terraform Init
      run: |
        cd infrastructure/dev/${{ github.event.inputs.infrapath }}
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID_DEV }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET_DEV }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID_DEV }}
        terraform init \
        -upgrade \
        -backend-config="resource_group_name=${{ env.RG_BACKEND }}" \
        -backend-config="storage_account_name=${{ env.ST_BACKEND }}" \
        -backend-config="container_name=${{ env.CONTAINER_BACKEND }}" \
        -backend-config="key=${{ github.event.inputs.infrapath }}/terraform.tfstate"
    
    - name: Terraform Validate
      run: |
        cd infrastructure/dev/${{ github.event.inputs.infrapath }}
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID_DEV }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET_DEV }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID_DEV }}
        terraform validate

    - name: Terraform Plan
      run: |
        cd infrastructure/dev/${{ github.event.inputs.infrapath }}
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID_DEV }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET_DEV }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID_DEV }}
        terraform plan -out=tfplan

    - name: Save Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ env.RUN_ID }}
        path: |
          infrastructure/dev/${{ github.event.inputs.infrapath }}/tfplan

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: [workflow-info, terraform-plan]
    if: github.event.inputs.infrapath != 'none'
    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Terraform Init
      run: |
        cd infrastructure/dev/${{ github.event.inputs.infrapath }}
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID_DEV }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET_DEV }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID_DEV }}
        terraform init \
        -upgrade \
        -backend-config="resource_group_name=${{ env.RG_BACKEND }}" \
        -backend-config="storage_account_name=${{ env.ST_BACKEND }}" \
        -backend-config="container_name=${{ env.CONTAINER_BACKEND }}" \
        -backend-config="key=${{ github.event.inputs.infrapath }}/terraform.tfstate"

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan-${{ env.RUN_ID }}
        path: |
          infrastructure/dev/${{ github.event.inputs.infrapath }}
    
    - name: Terraform Apply
      run: |
        cd infrastructure/dev/${{ github.event.inputs.infrapath }}
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID_DEV }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET_DEV }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID_DEV }}
        terraform apply -auto-approve tfplan